const shift = (number: number, shift: number): number => {
  return number * Math.pow(2, shift);
};

export enum DiscordPermissions {
  createInstantInvite = shift(1, 0),
  kickMembers = shift(1, 1),
  banMembers = shift(1, 2),
  administrator = shift(1, 3),
  manageChannels = shift(1, 4),
  manageGuild = shift(1, 5),
  addReactions = shift(1, 6),
  viewAuditLog = shift(1, 7),
  prioritySpeaker = shift(1, 8),
  stream = shift(1, 9),
  viewChannel = shift(1, 10),
  sendMessages = shift(1, 11),
  sendTTSMessages = shift(1, 12),
  manageMessages = shift(1, 13),
  embedLinks = shift(1, 14),
  attachFiles = shift(1, 15),
  readMessageHistory = shift(1, 16),
  mentionEveryone = shift(1, 17),
  useExternalEmojis = shift(1, 18),
  viewGuildInsights = shift(1, 19),
  connect = shift(1, 20),
  speak = shift(1, 21),
  muteMembers = shift(1, 22),
  deafenMembers = shift(1, 23),
  moveMembers = shift(1, 24),
  useVAD = shift(1, 25),
  changeNickname = shift(1, 26),
  manageNicknames = shift(1, 27),
  manageRoles = shift(1, 28),
  manageWebhooks = shift(1, 29),
  manageGuildExpressions = shift(1, 30),
  useApplicationCommands = shift(1, 31),
  requestToSpeak = shift(1, 32),
  manageEvents = shift(1, 33),
  manageThreads = shift(1, 34),
  createPublicThreads = shift(1, 35),
  createPrivateThreads = shift(1, 36),
  useExternalStickers = shift(1, 37),
  sendMessagesInThreads = shift(1, 38),
  useEmbeddedActivities = shift(1, 39),
  moderateMembers = shift(1, 40),
  viewCreatorMoentizationAnalytics = shift(1, 41),
  useSoundboard = shift(1, 42),
  createGuildExpressions = shift(1, 43),
  createEvents = shift(1, 44),
  useExternalSounds = shift(1, 45),
  sendVoiceMessages = shift(1, 46),
  sendPolls = shift(1, 49),
}
